### ISSUE TITLE
Speed problems when using Epoch

### ISSUE THREAD

**Issue by erscampbell** [postmatic/epoch#116]
Written on behalf of Leon:

The website shivamber.com has slowed down since installing Epoch. The site was tested on pingdom and results for epoch.api are 404.

Any ideas?

**Comment by shackep** [comment]
~~I am having a similar problem. I am using redirection plugin and I see dozens of 404s for the epoch.api.~~ I am going to chalk this up as pantheon specific as pantheon is doing to domain magic to handle how domains resolve. On my set environment I don't see any of this happening as the domain is set properly.

**Comment by Vernal** [comment]
Interesting. Thanks for the feedback about Pantheon, @shackep. We are about to roll out a program to help hosts better configure their systems to run Epoch and I'll add them to the list!

**Comment by Vernal** [comment]
PS - Tons of performance enhancements coming in the next few weeks. I haven't created issues for them yet as we are still in the specification stages. Keep an eye out.

**Comment by johndavidhunt** [comment]
I really like Epoch.
I am having a performance issue.
![Image showing 70% usage in 3 days by epoch-api](http://dailynous.com/wp-content/uploads/2015/12/dn_usage_2015-12-22_530_AM.png)

 This is from the media temple hosting account screen, showing that in the last 3 days we have gone over our allotment, and over 70% of our usage from the month is related to epoch-api in this time frame. We installed Epoch about 3 days ago and you can see the correlating spike in usage since then.
 I don't know how relevant it is, but we are using the [Heap theme](http://themeforest.net/item/heap-a-snappy-responsive-wordpress-blog-theme/7422943), and also several plugins from the list suggested by Postmatic for use with Epoch:
         [Crowd Control by Postmatic](https://wordpress.org/plugins/crowd-control/)
         [GoodBye Captcha](https://wordpress.org/plugins/goodbye-captcha/)
         [Postmatic - WordPress Subscriptions & Commenting by Email](https://wordpress.org/plugins/postmatic/)
         [Postmatic Social Commenting](https://wordpress.org/plugins/postmatic-social-commenting/)
         [Rating System](https://wordpress.org/plugins/rating-system/)

 The Epoch settings I am using are:
    "Use my typography and colors"

 I don't know what other details you need, but I am beginning to check all of the settings I am using to see what I can do change this. Any help given could be appreciated.

 Thanks. 

EDIT: I wonder if I should have opened a new issue for this, but I felt that I could tag along here since my site is taking up to 20 seconds to load the comments sometimes (site loads a little slow/normal, then epoch takes a long time to load after that). 
The site I reference is http://dailynous.com and it has about  10k-20k hits a day with lots of articles, and lots of comments.

**Comment by johndavidhunt** [comment]
Continuing to post here since this is where I started. It seems that (mildly) high traffic sites may not be suitable for Epoch?
The whole site is going down this morning so I had to pull/deactivate Epoch just to keep it from crashing. I assume that it was Epoch as things have stabilized now that I have reverted to the default commenting system for the system.

ERROR THAT SHOWED UP instead of site

Warning: mysqli_real_connect(): (42000/1203): User db1****\* already has more than 'max_user_connections' active connections in /nfs/c121/h0312/mnt/1923422331/domains/dailynous.com/html/wp-includes/wp-db.php on line 1488

**Comment by Vernal** [comment]
Hey John,

Interesting. That amount of traffic daily might be stretching it unless you switch Epoch into file-write mode. Have you tried this?
http://docs.gopostmatic.com/article/192-how-to-enable-even-lighter-weight-server-polling

I haven't tested that technique on MT yet but it works on the majority of hosts we attempt it on. Could you try it and report back to me? If you want to do it in realtime i'll be around today. Find me on chat in the footer of http://gopostmatic.com.

Jason

**Comment by Vernal** [comment]
PS - @shackep I'm guessing your problem was resolved a few releases ago..

**Comment by johndavidhunt** [comment]
Thanks Vernal, Will do, I'll try it and let you know...

**Comment by Vernal** [comment]
Sweet. Hit me up on chat if you run into any problems and/or questions.

On Tue, Dec 22, 2015 at 10:47 AM, John David Hunt notifications@github.com
wrote:

> Thanks Vernal, Will do, I'll try it and let you know...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/116#issuecomment-166652098.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by johndavidhunt** [comment]
The _file-write mode_ Vernal mentioned seemed to bring down resource consumption quite a bit! 
... but it's still using a substantial amount of processing just to run Epoch, my site was using an average of 4 GPU a day before, (a GPU is a unit of processing measurement that Media Temple uses), then after installing Epoch that jumped quite a lot.

Before Epoch average was about 4 'GPU'
Total Daily 'GPU' Usage after Epoch install
Day 1 : 757
Day 2 : 926
Day 3 : 2769
(started using file-write mode)
Day 4 : 143 (and only 8 hrs in to day so far...)

This image/report (like the one I sent above) shows that epoch-api is the one that is using a substantial amount of this. 

Dec
![Image showing usage change in site from epoch-api](http://dailynous.com/wp-content/uploads/2015/12/dailynous-mediatemple-gpu-2015-12-23-6am.png)

The ramp up towards the right starts about 4 days ago when I installed Epoch, and the high jump is a higher traffic day (with Epoch installed), before when we got 3 times the normal traffic it was no big deal going from 3GPU to 8GPU or so, but since 800GPU already is insanely substantial the 2769GPU being used is ridiculous. 

Before the file-write mode fix, epoch was using about 70% of the total processing usage of the site, (with an additional 1.5% being used for 404s to epoch-api). (You can see the drop where I began using the _file-write mode_.)

Dec 22
![Image showing usage for Dec 22 including 70 percent usage by epoch-api](http://dailynous.com/wp-content/uploads/2015/12/dailynous-mediatemple-gpu-for-2015-12-22-aken-on-2015-12-23-6am.png.png)

After the file-write mode fix, epoch makes up about 25% of total site processor usage, (with 404s of epoch-api being about 13%, since total epoch-api usage went down the 404s proportionally went up)

Dec 23 so far
![Image showing usage for Dec 23 with about 25% - 37% usage](http://dailynous.com/wp-content/uploads/2015/12/dailynous-mediatemple-gpu-for-2015-12-23-taken-on-2015-12-23-6am.png.png)

So the file-write mode was a big help! but we are still far away from our goal for performance, I'm not sure what else I can do to slim things down, especially because one of the other high resource users is admin-ajax.php which I assume apoch-api might be utilizing? I even trimmed down the regular usage of WordPress for the admin-ajax.php with [Heartbeat Control](https://wordpress.org/plugins/heartbeat-control/)  plugin. 

I have also tried some of the things suggested in some of the other issues. I have added the following lines to _robots.txt_
Disallow: /epoch-api
Disallow: /epoch-api/

...and I also went ahead and resaved the _permalinks_, currently set to:
/%year%/%monthnum%/%day%/%postname%/

I am also using a _redirection plugin_, _jetpack_, and _akismet_, I mention those as they were mentioned in other issue threads, I had deactivated them and didn't notice a difference so I re-enabled them, but I didn't do thorough testing.

I would love to get my usage back down to what it was (around 3 to 4 GPU a day or 0.1 to 0.2 GPU  an hour), but it is necessary to at least get it down to under 50 GPU/day or 2 GPU/hour. 
This goal is to get epoch working on dailynous.com while only increasing cpu/gpu usage to less than 10 times what it was before epoch, (that should be an easily acceptable goal in my opinion...)

(Sorry post is so long and sorry for posting so close to _Christmas_ time...)

Vernal was a lot of help yesterday in getting the file-write mode to slim things down (thanks!), any suggestions of where to go from here to eliminate _404s_ and slim done epoch-api usage all around?

**Comment by cyberhobo** [comment]
I think increasing the comment check interval in the settings may currently be your next best option. Longer times there may reduce your GPU usage proportionally to your traffic. That may get you by until fancier caching and polling methods are built.

**Comment by johndavidhunt** [comment]
Thanks for the response, yes, I'll go ahead and change the comment check interval.

Is there any idea as to why there are 404s for the epoch-api, it seems that I have a lot of them not matter what I change...(is it normal?).
Thanks again.

**Comment by Vernal** [comment]
Hey John!

That's an awesome writeup of the performance. Thanks for sharing it. We know there are performance improvements that need to be made as Epoch gets installed on larger and larger sites. And, well, i'm happy to see how well it is holding up on yours. 

We know we can do better and have plans to do so for 2.0 this winter. It'll be RESTful with a new javascript frontend. Let me know if you want to help :)

Regarding the 404's: i'm not sure. I can't figure out where those come from sometime. @Shelob9 do you have any ideas on that?

**Comment by johndavidhunt** [comment]
I wonder if this stackoverflow question may be related to what we are experiencing with the 404s. 
http://stackoverflow.com/questions/5760538/ajax-call-to-php-script-returns-404-error
thoughts?

**Comment by iagdotme** [comment]
Hi @Vernal I am wondering if there are any updates on this? It seems a similar to the (now closed) issue here - https://github.com/postmatic/epoch/issues/30

I've been having big site stability issues recently My blog has had quite an increase in traffic (which I suppose is a good thing) and gets around 130K page views per month. Some of my posts do have a lot of comments (some have around 150 and some over 500).

I have a managed cloud server provided by a hosting company. Their sys admin guy had to deactivate epoch because it was causing so many problems. Obviously I don't want this. Basically it seems that Epoch was making several call backs to the site per page request. Each request obviously was triggering more PHP scripts and memory usage. Each of these call backs was taking more than 2 seconds.
I've continued to see a huge number of 404s being reported in Google's search console and am surprised that this hasn't been sorted out yet.

**Comment by Vernal** [comment]
Legacy. Doesn't apply to 2.0.
