### ISSUE TITLE
Your comment was not accepted, please check that everything is filled out correctly.

### ISSUE THREAD

**Issue by shackep** [postmatic/epoch#118]
I am running into an issue where I get "Your comment was not accepted, please check that everything is filled out correctly." When submitting a comment while logged out.
I also seem to be getting some 404s on the epoch api.

I am hosting on pantheon and they are doing some domain handling behind the scenes.

![screen shot 2015-10-02 at 3 13 19 pm](https://cloud.githubusercontent.com/assets/3768614/10255426/5aafbdc0-6918-11e5-8e4c-a3c6497210ab.png)

**Comment by cyberhobo** [comment]
I was able to reproduce this with Akismet active, and then post the same comment succesfully with Akismet deactivated. That's all I've got for now.

**Comment by ruffrazor** [comment]
I have the same problem, can't seem to find the solution. Also emailed Postmatic Support about it. 

And I don't use Akismet.

This error seems to go with it.

success: false, data: "Access to the Epoch API from external sites is not enabled."}
data: "Access to the Epoch API from external sites is not enabled."
success: false

List of plugins I use:

Advanced Custom Fields
Advanced Custom Fields: Date and Time Picker  
Advanced Custom Fields: Options Page  
Advanced Excerpt
Epoch  
Export Featured Images
Jetpack by WordPress.com
Social
Varnish HTTP Purge  
WordPress Importer  
WordPress Popular Posts
Yoast SEO

**Comment by shackep** [comment]
I have tested turning off Akismet and there is no difference. I was able to get something out of the error log.

https://gist.github.com/shackep/20421d561009e980e90c

**Comment by Vernal** [comment]
Fantastic Peter. We've been trying to catch this one in the wild all week. Dylan, what can you gander from that log?

**Comment by shackep** [comment]
I am using timber twig to handle templating. But am not sure if that would be an issue.

**Comment by cyberhobo** [comment]
I don't see anything obvious in the log, which makes sense if the problem still occurs with Akismet deactivated. It seems that all three of us are hitting different issues.

@ruffrazor your issue is probably the easiest to work around, it looks like HTTP_REFERER and SERVER_NAME don't match on your host for some reason. You can turn that check off with this snippet:

```
add_filter( 'epoch_api_allow_other_origins', '__return_true' );
```

**Comment by fabiankay** [comment]
@cyberhobo I had the same issue. The Snippet you provided works. 
Your suggestion where the problem comes from seems to be right. My domain points to Wordpress installation via A-record - so this might be a problem.

**Comment by Vernal** [comment]
Ok. I'm guessing that we're seeing this problem new because that filter never used to be in place. It shipped with 1.0.5 I think.

So my hunch is that domain redirects (www https etc) are playing a role here by making Akismet and other spam plugins upset.

We put that filter in for a good reason - to prevent cross-site embedding of the epoch iframe. @cyberhobo maybe we can make it smarter somehow.... such as white listing requests which originate from the same domain name? Any ideas?

**Comment by shackep** [comment]
I was able to use this filter and make comments. I would guess that in my case it is likely the issue vernal stated. Would it be safe to use this for the time being until another smarter solution in place.
Thanks!

**Comment by cyberhobo** [comment]
Does anyone experiencing this have a way of getting these values on your installation?

`$_REQUEST['_wp_http_referer'] 
$_SERVER['HTTP_REFERER']
$_SERVER[ 'SERVER_NAME' ]
`

My hunch is that we should use `home_url()` instead of `$_SERVER[ 'SERVER_NAME' ]`, but I'd like to make sure the referer value isn't the source.

**Comment by Shelob9** [comment]
Close via 419605b which implements @cyberhobo proposed solution.

**Comment by tormondo** [comment]
I also have this problem. Didn't look at it closely, but it started straight from the first user registrations and does not seem to have any logic behind, since the "flawed" comment is eventually published (bg-colored white unlike normal comments bg-colored gray) with a little watch sign top-right. I am lost reading the meaning of this combination of facts. I'd say it's quite an unpleasant peculiarity.

Correlating my case with the ones described above, I have neither Jetpack (not installed) nor Akismet (not activated), I login from the same computer with the same IP in the same browser under different registered users and the admin. Other "mortal" users are able to publish, but one is somehow a freak under seemingly the same conditions. Even after promoting this user to Contributor it does not comment seamlessly. Mindbreaking experience.

A set of tests including multiple user registrations and successive logins to post a comment may help clarify the issue, I believe.

**Comment by tormondo** [comment]
Guys, I searched for the alert in the Epoch code and came down to epoch.min.js where replaced 'alert(epoch_translation.comment_rejected)' with 'true'. At least new non-admins can post. Otherwise any newly created users (from different IPs etc) could not.

Hoping one of you can find the bug and fix it soon.

**Comment by TheArcturian** [comment]
My readers have the same problem once in a while. Usually it works again if the user just waits a few minutes. Any fix on this?
