### ISSUE TITLE
Epoch breaks slightly when using my typography and colors

### ISSUE THREAD

**Issue by ovizii** [postmatic/epoch#127]
Screenshot of my original comment form without epoch: http://screencast.com/t/axMiZgr8njs 
Screenshot of my comment form with epoch: http://screencast.com/t/TLbtSa3xEWqA 

I tried commenting with epoch set to use my styles and colors and am getting this when trying to comment: http://screencast.com/t/coJpdH6ht1i  but if I simply submit the same again I get: http://screencast.com/t/HQSUBf0t  which says its a duplicate content....

It appears Akismet caught me as SPAM so I unspammed the comments and approved them. Will I still get notifications about these comments and replies or has Akismet broken the chain?

**Comment by Vernal** [comment]
The issue of the form fields laying out funky has something to do with your theme. Epoch does its best to override.... in your case adding this css should work:
#commentform label {width: auto !important;}

The other error you mention is a known bug which will be fixed in the next release.

Best,
Jason

**Comment by ovizii** [comment]
Thx for the css snippet and for acknowledging the other issue
