### ISSUE TITLE
Uncaught ReferenceError: id is not defined

### ISSUE THREAD

**Issue by tysonsukeforth** [postmatic/epoch#157]
I've created a new site with Epoch as one of the plugins, but whenever one posts a comment no comment actually gets posted and the console throws the error "Uncaught ReferenceError: id is not defined". I've disabled all other plugins and reinstalled Epoch to make sure there are no conflicts and the error persists. It's not that complex of a site so I'm unsure what I could have done on my end.

You can see for yourself at http://enpsychlomedia.com/im-free/ if it helps.

Full error:

Uncaught ReferenceError: id is not defined
d @ epoch.min.js?ver=1.0.12:1
(anonymous function) @ epoch.min.js?ver=1.0.12:1
m.event.dispatch @ jquery.js?ver=1.11.3:4
r.handle @ jquery.js?ver=1.11.3:4

**Comment by timbakkum** [comment]
Got exactly the same error. Happens when you click the post comment button. Plugin was working fine before on my local dev, but stopped working when I moved theme online and updated all the plugins + wp to latest version. Thanks in advance for any help!

02:46:02.545 ReferenceError: id is not defined
d() epoch.min.js:1
b.init/<() epoch.min.js:1
m.event.dispatch() jquery.js:4
m.event.add/r.handle() jquery.js:4
1 epoch.min.js:1:1895

**Comment by tysonsukeforth** [comment]
I also had just moved it from my local dev to production. Not sure how likely it is but I wonder if the database migration had anything to do with it. I used Duplicator because I'm lazy like that and it works great for me 99% of the time, part of the deployment process is an automatic search and replace on the db.

**Comment by Vernal** [comment]
Yep. This is a totally huge and awful bug. Fix coming today.

**Comment by tysonsukeforth** [comment]
Awesome, thanks for the update!

**Comment by timbakkum** [comment]
Thanks a lot for the quick fix !

**Comment by Vernal** [comment]
Sure thing. Today's release is just a rollback to the 1.0.10 code base. It rips out the fast commenting introduced in 1.11 until we get it right.
