### ISSUE TITLE
Comments are stored without content

### ISSUE THREAD

**Issue by schlessera** [postmatic/epoch#185]
When Epoch is active on my site, all new comments are stored as empty comments, without any body text.

As soon as I disable Epoch, commenting works as expected.

Site: https://www.alainschlesser.com/

**Comment by Vernal** [comment]
Hey Alain,

When Epoch is enabled are there any console errors in your browser?

Jason

**Comment by schlessera** [comment]
No, no console output.

**Comment by Vernal** [comment]
Interesting. Where is your site hosted and what sort of CDN or cache do you have in place?

On March 17, 2016 at 9:13:09 AM, Alain Schlesser (notifications@github.com) wrote:

No, no console output.

**Comment by schlessera** [comment]
It is hosted at Siteground, on a Reseller plan, which should be equivalent to the StartUp plan (https://www.siteground.com/web-hosting.htm).

Siteground has its own caching system called `SuperCacher`, but only the static portion of that should be enabled on the reseller plan, afaik.

I don't use a CDN for that site, it is a very basic blog.

**Comment by Vernal** [comment]
Hey Alain,

I’ve tested things on site ground and I can’t make sense of this. It must be an unknown conflict with another plugin :(

If you care to take it another step further could you get me a list of active plugins?

On March 17, 2016 at 9:17:27 AM, Alain Schlesser (notifications@github.com) wrote:

It is hosted at Siteground, on a Reseller plan, which should be equivalent to the StartUp plan (https://www.siteground.com/web-hosting.htm).

Siteground has its own caching system called SuperCacher, but only the static portion of that should be enabled on the reseller plan, afaik.

I don't use a CDN for that site, it is a very basic blog.

**Comment by schlessera** [comment]
Hey Jason,

I went through the plugins on my site and could pinpoint the issue to be an incompatibility between Epoch and [Antispam Bee](https://github.com/pluginkollektiv/antispam-bee).

I'll investigate some more...

**Comment by schlessera** [comment]
The issue is that Antispam Bee hides the normal comment `textarea` (`.comment`), and adds a new one with an ID that includes a hash (`#bc1e5-comment` in my case). Although the spam check is circumvented by the Epoch endpoint mechanism, submitting the comment fails nevertheless because retrieves the comment text from the empty hidden `textarea`, instead of the newly created one from Antispam Bee.

I introduced a [ticket](https://github.com/pluginkollektiv/antispam-bee/issues/28) with Antispam Bee to ask how best to retrieve the `$secret` hash name of the new `textarea`.

**Comment by Vernal** [comment]
Whoa!!! Nice sleuthing! I’ll keep an eye on that ticket!

On March 23, 2016 at 9:28:49 AM, Alain Schlesser (notifications@github.com) wrote:

The issue is that Antispam Bee hides the normal comment textarea (.comment), and adds a new one with an ID that includes a hash (#bc1e5-comment in my case). Although the spam check is circumvented by the Epoch endpoint mechanism, submitting the comment fails nevertheless because retrieves the comment text from the empty hidden textarea, instead of the newly created one from Antispam Bee.

I introduced a ticket with Antispam Bee to ask how best to retrieve the $secret hash name of the new textarea.

**Comment by Vernal** [comment]
And for the record…. we’ve got a recommended setup for anti spam here:
http://docs.gopostmatic.com/article/123-what-anti-spam-plugins-and-techniques-do-you-recommend

On March 23, 2016 at 10:13:38 AM, Jason Lemieux (jason.lemieux@gmail.com) wrote:

Whoa!!! Nice sleuthing! I’ll keep an eye on that ticket!

On March 23, 2016 at 9:28:49 AM, Alain Schlesser (notifications@github.com) wrote:

The issue is that Antispam Bee hides the normal comment textarea (.comment), and adds a new one with an ID that includes a hash (#bc1e5-comment in my case). Although the spam check is circumvented by the Epoch endpoint mechanism, submitting the comment fails nevertheless because retrieves the comment text from the empty hidden textarea, instead of the newly created one from Antispam Bee.

I introduced a ticket with Antispam Bee to ask how best to retrieve the $secret hash name of the new textarea.

**Comment by schlessera** [comment]
Thanks for the antispam recommendations. Both of the solutions you're suggesting for antispam (Akismet & CleanTalk) are not an option, though, as they have legal repercussions.

They infringe upon data privacy laws in many countries (and the entire European Union) because they send a visitor's private data to a third-party without the visitor's prior consent. I would need to add all sorts of legalese just to use these...

**Comment by Vernal** [comment]
I hear you.

If you do find a set up which works for you and complies with local laws please share it with us! We will add it to our documentation.

Jason

On March 23, 2016 at 10:25:39 AM, Alain Schlesser (notifications@github.com) wrote:

Thanks for the antispam recommendations. Both of the solutions you're suggesting for antispam (Akismet & CleanTalk) are not an option, though, as they have legal repercussions.

They infringe upon data privacy laws in many countries (and the entire European Union) because they send a visitor's private data to a third-party without the visitor's prior consent. I would need to add all sorts of legalese just to use these...
