### ISSUE TITLE
'Completely (beta)' not formatting correctly

### ISSUE THREAD

**Issue by HandyGadget** [postmatic/epoch#190]
You left a message at [https://wpfunder.org/corpses-in-the-repo/#comment-8](https://wpfunder.org/corpses-in-the-repo/#comment-8) but I think it was earlier when I was using a different Epoch profile.

The 'Completely (beta)' has a much better look and feel but for the fact that the message box disappears of the right hand side of the screen.

If you click on that link you will see what I mean.

Is there an update due out for WP4.5 compatibility and if so, might it contain a fix for 'Completely (beta)'?

**Comment by Vernal** [comment]
Hey Terence,

I’m not sure why Divi hates Epoch so much but am not going to worry about it for now as we are knee deep in Epoch 2 development. For now this should fix the problem for you:

epoch-wrap {width: 100% !important;}

Best,
Jason

On April 25, 2016 at 3:08:08 AM, Terence Milbourn (notifications@github.com) wrote:

You left a message at https://wpfunder.org/corpses-in-the-repo/#comment-8 but I think it was earlier when I was using a different Epoch profile.

The 'Completely (beta)' has a much better look and feel but for the fact that the message box disappears of the right hand side of the screen.

If you click on that link you will see what I mean.

Is there an update due out for WP4.5 compatibility and if so, might it contain a fix for 'Completely (beta)'?

**Comment by HandyGadget** [comment]
Thanks Vernal, but that doesn't help.

This is the line which appears to be causing the problem ...

`<div id="epoch-wrap" class="comments-area epoch-wrapper" style="width: 1874px">`

Changing it to ...

`<div id="epoch-wrap" class="comments-area epoch-wrapper" style="width: 100%;">`

seems to do the trick.

Terence.

**Comment by HandyGadget** [comment]
OK, I know its not very elegant but I solved my problem with this for the time being ...

```
#epoch-comments {
    width: 50% !important;
}

```

Terence.

**Comment by HandyGadget** [comment]
Ooops!  I spoke too soon. 100% works on the single page where there is a sidebar, but not in the blog section where there isn't one. And 50% works on the blog, where there is no sidebar, but not in the single page, where there is one. See what I am saying, it works here ~ https://wpfunder.org/campaigns/aliexpress-affiliate/ ~ but not here ~ https://wpfunder.org/corpses-in-the-repo/

**Comment by visualdatasolutions** [comment]
Hi Terence,
it seems there is a conflict between your theme and Epoch js.  could you try commenting out the code resetting the width and see whether it helps?  The easy way is to go to classes/core.php, look for the following line and comment it out:
add_filter( 'the_content', array( '\postmatic\epoch\front\layout', 'width_sniffer' ), 100 );

This will avoid outputting the html code for sniffing, so the width of div element can be set by your theme. 
Best regards.

Oliver

**Comment by Vernal** [comment]
Thank you for chiming in, Oliver! We’ve been busy and you lending a hand means a lot.

Best,
Jason

On April 26, 2016 at 10:55:51 PM, Oliver Liu (notifications@github.com) wrote:

Hi Terence,
it seems there is a conflict between your theme and Epoch js. could you try commenting out the code resetting the width and see whether it helps? The easy way is to go to classes/core.php, look for the following line and comment it out:
add_filter( 'the_content', array( '\postmatic\epoch\front\layout', 'width_sniffer' ), 100 );

This will avoid outputting the html code for sniffing, so the width of div element can be set by your theme.
Best regards.

Oliver

**Comment by HandyGadget** [comment]
Sorry to say it made no difference to comment out the line.

But looking on the bright site, at least that eliminates one place the problem is NOT coming from.

**Comment by visualdatasolutions** [comment]
Hi Jason,  
No worries. I happened to know this plugin well enough to answer a few questions other users might have. 

Hi Terence, 

sorry for the confusion and thank you for your patience. I checked the core.php source file again and there are actually two lines containing the same filter, please comment both lines out. 

Have you enabled any caching or CDN? could you purge the cache and see whether the issue is resolved? 

The way epoch.min.js works is that it will look for the width of the parent element of the following element:

`<div id="epoch-width-sniffer"></div>`

Once found, it will use this width to add style to the element "epoch-wrap", that is why you saw the following code in your previous comment.
`<div id="epoch-wrap" class="comments-area epoch-wrapper" style="width: 1874px">`

epoch-width-sniffer is generated by the filter mentioned in my previous comment. If you comment out both lines, epoch-width-sniffer should disappear too. If it is still there, it must be from cached version. 

alternatively you may back up epoch.min.js, and comment out or delete  TWO b.set_width() in the following file.
 epoch/assets/js/front/epoch.min.js

 Javascript code is minified and much harder to read.  Let's try the easy way to comment out the other line in core.php, and clear the cache and see whether the issue is gone. 

best regards

Oliver

**Comment by HandyGadget** [comment]
Oliver ~ spot on!  That' fixed it, and I now have a comment entry box and comments all the right size for the page layout.

Thank you for your help

**Comment by visualdatasolutions** [comment]
I am glad it works for you and you have solved the problem. By the way, your website looks awesome.  Looking forward to seeing it again when it is finished 
best regards. 
Oliver

**Comment by HandyGadget** [comment]
Thanks Oliver,

Maybe the WordPress community will find it useful. 

Maybe not.

We shall have to see. 

Terence.

**Comment by Vernal** [comment]
Yes. Thanks, Oliver!

On April 29, 2016 at 7:55:51 PM, Terence Milbourn (notifications@github.com) wrote:

Thanks Oliver,

Maybe the WordPress community will find it useful.

Maybe not.

We shall have to see.

Terence.
