### ISSUE TITLE
ensure jquery 3.0 compatibility 

### ISSUE THREAD

**Issue by saltnpixels** [postmatic/epoch#227]
Your code does not work with jquery 3.0
You need to change .fail to .error and .success to .done on your post functions

**Comment by Vernal** [comment]
I haven't had a chance to try this with the 2.0 branch. Have a go, @jekkilekki ?

**Comment by jekkilekki** [comment]
Let me try take a look at it tomorrow.

**Comment by Vernal** [comment]
Thanks man!

**Comment by Vernal** [comment]
Hey @jekkilekki any luck?

**Comment by jekkilekki** [comment]
@Vernal Sorry, had another project I had to push last week.

Actually, there doesn't seem to be any problem on the `2.0-dev` branch with this. (I cloned the `2.0-dev` branch - that's the correct one, right?)

There's no Composer stuff in the `2.0-dev` branch, so I just activated the plugin and started reading it over. Couldn't find any `.fail` nor `.success` code anywhere in the JS files - even did a "Find..." and it turned up nothing.  (Those look like AJAX commands to me, right? - but since you're now implementing this with the REST API, it seems that those commands have been totally replaced on `2.0-dev`.)

If that's the case, you can just go ahead and close this. Or, if I'm misunderstanding where to find this - please redirect me.

**Comment by Vernal** [comment]
Nope, I think we are good. Thanks for checking!
