### ISSUE TITLE
Epoch is killing servers?

### ISSUE THREAD

**Issue by erscampbell** [postmatic/epoch#44]
I just want to let you know that while I was working last night on the integration with GoodBye Captcha… it was a pain for me because Epoch was sending Ajax requests like crazy causing my browser to freeze.

Today I installed Epoch at work! Same thing! At work I have a more powerful computer and the requests are handled but… this should not happen at all. Comment Check Interval option is set to 180 seconds and is totally ignored

I have no idea if you are aware of this or somebody else reported it. Just wanted to let you know!

**Comment by Shelob9** [comment]
@erscampbell Yes, turns out that setting was always getting reset to 15 seconds. This is fixed in 1.0.1 Thanks for pointing this out.

This plugin sends lots of AJAX requests by definition. Most of them just check comment count and die, and shouldn't kill any reasonable server, though not everyone has a reasonable server... We are working on some optimization strategies.
