### ISSUE TITLE
Theme style: None?

### ISSUE THREAD

**Issue by leonuts** [postmatic/epoch#78]
In version 1.0.2 there are 3 types of theme—Complete, Use my typo, and minimal. Is there an option to leave the front end comment as it is? I've chosen minimal but there's still a layout issue (And I'm using twenty fourteen theme).

**Comment by mundschenk-at** [comment]
"Layout issues" is a bit of an understatement. I'm currently trying to integrate Epoch into my existing comment theme and it appears to be a futile effort. Even the "minimal" option (what is called "none" in the code, I believe) still rewrites the structure of my comment code completely. 

Instead of
`<section id="comments">`
`<h2>2 Kommentare</h2>`
`<ul id="singlecomments" class="commentlist">`
`<li id="li-comment-13122" class="comment even thread-even depth-1">`
`<li id="li-comment-13123" class="comment byuser comment-author-mave bypostauthor odd alt thread-odd thread-alt depth-1">`
`<article id="comment-13123">`
`<header class="comment-meta-wrap">`
`<p>`
`<p>`
`<div class="reply"> </div>`
`</article>`
`</li>` 
`</ul>`
we get 
`<div id="comments" class="comments-area epoch-wrapper" style="width: 540px;">`
`<div id="epoch-comments">`
`<ol class="comment-list commentlist ">`
`<li id="comment-145" class="comment" data-comment-id="145">`
`<article id="div-comment-145" class="comment-body">`
`<footer class="comment-meta">`
`<div class="comment-content">`
`<p>Epoch Test</p>`
`</div>`
`<div class="reply" data-comment-id="145"> </div>`
`</article>`
`</li>`
`</ol>`
`<ol class="comment-list commentlist ">`
`<ol class="comment-list commentlist ">`
...`

Now I could try to get that markup to superficially look like the current one, but it would still be a mess structurally.

**Comment by Vernal** [comment]
Hey Pep,

Maybe this is a language issue. The minimal setting works by making the assumption that your comment area is rendered by the default output of [comment-template.php](https://core.trac.wordpress.org/browser/tags/4.3/src/wp-includes/comment-template.php). That's all. For themes that do use comment-template.php it's a nice fit. For those that don't.... not so much.

This is pretty close to #84 so I'll close this and let's continue there.

**Comment by mundschenk-at** [comment]
What do you mean by "default output"? When no comments.php template (and no callback functions for customized individual comments markup) is present?
