### ISSUE TITLE
Display pending comments on page refresh

### ISSUE THREAD

**Issue by Vernal** [postmatic/epoch#89]
This would be sweet especially if it worked with simple comment editing. Best to make a unique branch pulled off of master for this one. What do you think @ronalfy ?

**Comment by ronalfy** [comment]
Yes, a new branch would be preferred.

**Comment by Vernal** [comment]
I made you a contributor. You should be able to branch it...

On Wed, Sep 9, 2015 at 2:13 PM, Ronald Huereca notifications@github.com
wrote:

> Yes, a new branch would be preferred.
> On Wed, Sep 9, 2015 at 12:19 Vernal notifications@github.com wrote:
> 
> > This would be sweet especially if it worked with simple comment editing.
> > Best to make a unique branch pulled off of master for this one. What do
> > you
> > think @ronalfy https://github.com/ronalfy ?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/postmatic/epoch/issues/89.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/89#issuecomment-138995382.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059

**Comment by ronalfy** [comment]
Oooh, I feel the power.

**Comment by ronalfy** [comment]
@Vernal sorry to trouble you, but it looks like I do not have contributor access and must fork and do a pull request?

**Comment by Vernal** [comment]
I sent you an invite via github. It says it is still pending. Check https://github.com/postmatic

**Comment by ronalfy** [comment]
Please check out https://github.com/postmatic/epoch/tree/comment-moderation-refresh

The thing I'm most worried about is https://github.com/postmatic/epoch/commit/d6670dffddbdf86d2588dcb26528bccde70fde00.

This appears to affect the comment number (There are 4 comments), when there are only two publicly approved comments.

This number cannot be 0 in order to show moderated comments, so there's still some digging to do here in order to show the correct number of public comments on the front-end.

Test by setting discussion settings to moderation only and log out. Open a 2nd incognito browser and log in as admin.

WordPress internally uses the e-mail address/cookie to check for existing moderated comments, FYI.

Test 1:
1. Brand new empty post.
2. Leave a comment using your e-mail address 
3. Refresh

Test 2:
1. Brand new empty post
2. Admin leaves comment
3. User leaves comment using e-mail address
4. Refresh

Test 3:
1. Brand new empty post
2. User leaves comment. 
3. Refresh.
4. Admin leaves comment.
5. User doesn't refresh, admin comment shows

**Comment by ronalfy** [comment]
BTW, the above (setting the comment cookies) has the very favorable effect of remembering your name, email, url, etc in Epoch. Something that didn't happen before.

**Comment by ronalfy** [comment]
Sorry to ramble.

With https://github.com/postmatic/epoch/commit/1f55895dc0a99a3745724ee62b9c9ef7a55030ca I consider this issue ready for testing.

All is well and the unicorns are dancing.

**Comment by Vernal** [comment]
Yea man. Serious freaking unicorns! This is incredible.

I only see one potential failure. It's an edge case and i'm not overly worried about it... but you might want to check on it. Try this:

Test 4 (requires Simple Comment Editing):
1. Brand new empty post
2. User leaves comment.
3. Comment edit box is visible.
4. Refresh.
5. Comment edit box is visible.
6. Admin leaves comment.
7. User doesn't refresh, admin comment shows
8. Refresh.
9. Comment edit box is missing.

Again. Not a biggie. This is incredible regardless, but if you want to fix it go ahead. Otherwise, I sign off on this and consider it closed.

**Comment by ronalfy** [comment]
I saw that yesterday, but I couldn't always duplicate it. Sometimes it worked sometimes It didn't.

If you don't consider this a show stopper, let's proceed because it may be something on SCE's end.

I'm busy preparing for WordCamp DFW, so if you want to get this out, let's close this ticket and add a new issue and I'll get to it when I can.

What do you think?

**Comment by Vernal** [comment]
Sounds great. Nice work!

On Thu, Sep 10, 2015 at 11:47 AM, Ronald Huereca notifications@github.com
wrote:

> I saw that yesterday, but I couldn't always duplicate it. Sometimes it
> worked sometimes It didn't.
> 
> If you don't consider this a show stopper, let's proceed because it may be
> something on SCE's end.
> 
> I'm busy preparing for WordCamp DFW, so if you want to get this out, let's
> close this ticket and add a new issue and I'll get to it when I can.
> 
> What do you think?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/postmatic/epoch/issues/89#issuecomment-139287213.

## 

Jason G. Lemieux | Creative Director
Vernal Creative and Strategy
http://www.vernalcreative.com | _New Number_ - 802.821.4059
